### ISSUE TITLE
 Unexpected token export | export { WindowRef };

### ISSUE THREAD

**Issue by frontr-uk** [agm-preview/angular-google-maps#7]
Build on angular universal prod
SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/dist/ssr/main.js:18785:18)
/app/node_modules/@agm-preview/core/utils/browser-globals.js:7
export { WindowRef };

**Comment by michaelbats** [comment]
The keyword 'export' is unexpected token? It's literally this piece of code throwing the error: 
``` 
export class WindowRef {
  getNativeWindow(): any { return window; }
}
```

When does this occur?  you gotta have more details about context & stuff
